name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Validate Terraform modules recursively
        run: ./scripts/tf-validate.sh

      - uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: terraform-docs/terraform-docs
          cache: enable

      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
